// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doajqqrwyvchlncwdcdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvYWpxcXJ3eXZjaGxuY3dkY2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MjcyMTAsImV4cCI6MjA1NjUwMzIxMH0.wH1WRlPBCRXpkefyycEHdZoSkorCAigyKWpYcEq_wgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);